# Site settings
title: Grube's Dev Blog
description: > # this means to ignore newlines until "baseurl:"
  My personal development blog. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mgrube.github.io" # the base hostname & protocol for your site
twitter_username: michaelgrube
github_username:  mgrube

# Build settings
#markdown: kramdown
