# Site settings
title: Rhizome
description: > # this means to ignore newlines until "baseurl:"
  My own development blog!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: michaelgrube
github_username:  mgrube

# Build settings
markdown: kramdown
